# Generated by Django 2.2.7 on 2019-11-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.TextField(max_length=30)),
                ('value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('theType', models.TextField(max_length=30)),
            ],
        ),
    ]
