# Generated by Django 2.2.7 on 2019-11-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversions',
        ),
    ]
